version: '3.5'

services:
  php:
    build:
      context: docker
    user: 1000:1000
    environment:
      PHP_IDE_CONFIG: "serverName=valueObject"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /workspace
    volumes:
      - .:/workspace
