version: '3.5'

services:
  php:
    build:
      context: docker
    environment:
      PHP_IDE_CONFIG: "serverName=valueObject"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    working_dir: /workspace
    volumes:
      - .:/workspace
      - ~/.composer:/home/pagamenti/.composer
